### ISSUE TITLE
Missing and ignored words

### ISSUE THREAD

**Issue by humdingerb** [janus2/WordClock#2]
The English version could do with an "A", e.g. "It Is **A** Quarter To Three".

The "Past" seems to be ignored for e.g. 3:30: It says "It Is Half Three" instead of "It Is Half Past Three".

**Comment by janus2** [comment]
The A is missing from all the wordclocks I "consulted" ;-) I think because "Quarter Twenty" is the longest line and could  ruin the balance of the space between the words...   The second problem is because I am dumb

**Comment by humdingerb** [comment]
Yes, the "A" is optional and not really needed, come to think of it.

> The second problem is because I am dumb

You're still a pretty good coder, all things considered... :)
